### ISSUE TITLE
No file named config_datasets.json is created after installation

### ISSUE THREAD

**Issue by dataUnNest** [adswerve/google_analytics_flattener#10]
Hello,

The installation process went well and without hiccups up until the last part. 

<img width="408" alt="image" src="https://user-images.githubusercontent.com/91544177/141777339-0dc7bb63-c332-4927-8200-d5b6c9d82f4c.png">
All the buckets were created properly but no config file was created in gs://[Deployment Name]-[PROJECT_NUMBER]-adswerve-ga-flat-config/ 
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/91544177/141777483-e190a223-26d0-4ef3-80c9-23387833a072.png">

The only warning message I got at some point was : 

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/91544177/141777770-086b1534-176c-4b1a-a66f-a024963b4cc8.png">

When I try to trigger a backfill, nothing on BigQuery happens, I'm assuming it is because of this missing file.

**Comment by iamnutzy1975** [comment]
A couple things to check:

1.
Trigger (execute) the cloud function (with a blank message) named [Deployment Name]-cfconfigbuilderps. It will create the necessary configuration file in the applications Google Coud Storage bucket. An easy method to do this is to browse to https://console.cloud.google.com/functions and click the cloud function named [Deployment Name]-cfconfigbuilderps and go to the testing section and click "TEST THIS FUNCTION".  

Check the logs to make sure this function is executing without error.  

2. If the cloud function above is executing without error, can you confirm there is a BigQuery dataset named with only digits (numbers) and contains a data-shared table with prefix "ga_sessions" and suffix of 8 digits (YYYYMMDD)

**Comment by dataUnNest** [comment]
I'm under the impression that the dataset location is the issue, it doesn't seem to be possible to select US multiregion in the .yaml files. I don't know if it's a limitation of the cloud functions

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/91544177/141823553-d34c81db-0e50-4387-8e8b-f0c64793768e.png">

But I will recreate the deployment to test the function at https://console.cloud.google.com/functions

**Comment by dataUnNest** [comment]
It is indeed crashing 
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/91544177/141826159-9e16496f-f456-472b-9035-be7ef45e4e47.png">
I'm wondering if all the things I tried today may have caused more problems because when deploying again after trying a fix for the region issue, it finished with an error that shouldn't be here and seem to be an artifact of an earlier cloud shell command.
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/91544177/141826410-ce090c39-104d-4c6b-962c-a98dd9be04ba.png">


I will try tomorrow on a fresh project if I can manage to get a dataset in a region that works fine

**Comment by dataUnNest** [comment]
It finally worked, starting on a fresh plate indeed helped. Also I didn't know the dataset needed to only be numbers, I had cloned ga_sessions_YYYYMMDD in a dataset named test or something, maybe that's why initially there wasn't any config file. 
Thanks for helping!
